### ISSUE TITLE
Showcase demo edit button is broken

### ISSUE THREAD

**Issue by DataPhaseDan** [maplibre/ngx-maplibre-gl#43]
hi there,

first of all, thanks for your work. I have a problem to get the demo running.

It builds, but no map is displayed. 

I looked up your code on the Israel Hiking Map and did it like your code.

also tried the exact versions on the Hiking Map still nothing.

What am i doing wrong?
Thanks

```
import { Component,OnInit, ViewChild, ElementRef, AfterViewInit, OnDestroy } from '@angular/core';
import { MapComponent, NgxMapLibreGLModule,  } from '@maplibre/ngx-maplibre-gl';
import { Map } from 'maplibre-gl';
import { MapHolderService } from './map-holder.service';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'EcoMaps';
  
  public mapComponent!: MapComponent;

  constructor(private mapHolder: MapHolderService) {}

  public mapLoaded()
  {
    this.mapHolder.setMap(this.mapComponent.mapInstance);
  }

}
```
```
import { Injectable } from '@angular/core';
import { MapComponent, NgxMapLibreGLModule } from '@maplibre/ngx-maplibre-gl';
import { Map } from 'maplibre-gl';

@Injectable()
export class MapHolderService {

  public map!: Map;
  constructor() { }

  setMap(map: Map)
  {
    this.map = map;
  }
}
```
```
<mgl-map
[style]="'https://demotiles.maplibre.org/style.json'"
[zoom]="[9]"
[center]="[-74.5, 40]"
(mapLoad)="mapLoaded()"
>
</mgl-map>
```

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>EcoMaps</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
    <app-root></app-root>

  
</body>
</html>
```
```
{
  "name": "eco-maps",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.3.0",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@angular/router": "~13.3.0",
    "@maplibre/ngx-maplibre-gl": "^12.0.0",
    "maplibre-gl": "^2.1.9",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.3",
    "@angular/cli": "~13.3.3",
    "@angular/compiler-cli": "~13.3.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.6.2"
  }
}

```
```
Node.js version v17.7.1 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   3.18 MB |
polyfills.js          | polyfills     | 294.86 kB |
styles.css, styles.js | styles        | 240.38 kB |
main.js               | main          |  12.18 kB |
runtime.js            | runtime       |   6.51 kB |

                      | Initial Total |   3.72 MB

Build at: 2022-05-01T21:40:08.327Z - Hash: d52c7fc9b8727dbc - Time: 2766ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


√ Compiled successfully.
✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2022-05-01T21:40:08.528Z - Hash: d52c7fc9b8727dbc - Time: 97ms

√ Compiled successfully.
```

**Comment by HarelM** [comment]
This repo is maintained.
I'm using node 16 and not 17 which might cause issues.
You can have a look at the demo code to see how it is built.
I have tested it recently and it worked, so I'm not sure how to help here unfortunately...

**Comment by DataPhaseDan** [comment]
Hi,

thanks for your reply. I also used the actual LTS Version of node still no luck... guess i have to stick to a old version, i cant figure it out to get it running.

**Comment by HarelM** [comment]
You can check the following:
https://maplibre.org/ngx-maplibre-gl/demo/display-map
You can click the edit button in the upper right corner to see the code.

**Comment by DataPhaseDan** [comment]
yeah if i try i get a error, even on stackblitz

**Comment by HarelM** [comment]
Can you share a stackbliz with the error?

**Comment by DataPhaseDan** [comment]
```
Error in /turbo_modules/@angular/core@12.1.0/bundles/core.umd.js (4346:19)
Angular JIT compilation failed: '@angular/compiler' not loaded!
- JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
- Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
- Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
```

```Unhandled Promise rejection:
Angular JIT compilation failed: '@angular/compiler' not loaded!
- JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
- Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
- Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
; Zone:
<root>
; Task:
null
; Value:
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
- JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
- Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
- Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
- JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
- Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
- Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
at getCompilerFacade (https://txflie--run.stackblitz.io/turbo_modules/@angular/core@12.1.0/bundles/core.umd.js:4346:19)
at Object.ɵɵngDeclareFactory (https://txflie--run.stackblitz.io/turbo_modules/@angular/core@12.1.0/bundles/core.umd.js:33937:24)
at Object.eval (https://txflie--run.stackblitz.io/turbo_modules/@angular/forms@13.3.5/fesm2015/forms.mjs:93:36)
at eval (https://txflie--run.stackblitz.io/turbo_modules/@angular/forms@13.3.5/fesm2015/forms.mjs:7295:4)
at eval (https://txflie--run.stackblitz.io/turbo_modules/@angular/forms@13.3.5/fesm2015/forms.mjs:7296:3)
at eval (<anonymous>)
at Qt (https://c.staticblitz.com/d/webcontainer.2289b255d2f1f7fce446a3938a878ba992b69534.js:15:30145)
at https://c.staticblitz.com/d/webcontainer.2289b255d2f1f7fce446a3938a878ba992b69534.js:15:38799
at U (https://c.staticblitz.com/d/webcontainer.2289b255d2f1f7fce446a3938a878ba992b69534.js:15:13565)
at https://c.staticblitz.com/d/webcontainer.2289b255d2f1f7fce446a3938a878ba992b69534.js:15:13207
core.umd.js:4346
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
- JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
- Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
- Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
Unhandled Promise rejection:
Angular JIT compilation failed: '@angular/compiler' not loaded!
- JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
- Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
- Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
; Zone:
<root>
; Task:
null
; Value:
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
- JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
- Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
- Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
- JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
- Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
- Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
at getCompilerFacade (https://txflie--run.stackblitz.io/turbo_modules/@angular/core@12.1.0/bundles/core.umd.js:4346:19)
at Object.ɵɵngDeclareFactory (https://txflie--run.stackblitz.io/turbo_modules/@angular/core@12.1.0/bundles/core.umd.js:33937:24)
at Object.eval (https://txflie--run.stackblitz.io/turbo_modules/@angular/forms@13.3.5/fesm2015/forms.mjs:93:36)
at eval (https://txflie--run.stackblitz.io/turbo_modules/@angular/forms@13.3.5/fesm2015/forms.mjs:7295:4)
at eval (https://txflie--run.stackblitz.io/turbo_modules/@angular/forms@13.3.5/fesm2015/forms.mjs:7296:3)
at eval (<anonymous>)
at Qt (https://c.staticblitz.com/d/webcontainer.2289b255d2f1f7fce446a3938a878ba992b69534.js:15:30145)
at https://c.staticblitz.com/d/webcontainer.2289b255d2f1f7fce446a3938a878ba992b69534.js:15:38799
at U (https://c.staticblitz.com/d/webcontainer.2289b255d2f1f7fce446a3938a878ba992b69534.js:15:13565)
at https://c.staticblitz.com/d/webcontainer.2289b255d2f1f7fce446a3938a878ba992b69534.js:15:13207
core.umd.js:4346
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
- JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
- Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
- Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.```

**Comment by HarelM** [comment]
I need to see a stack blitz to be able to help...

**Comment by DataPhaseDan** [comment]
Just click the demo and press edit. 
(https://maplibre.org/ngx-maplibre-gl/demo/display-map)

it always generates a new fork on stackblitz so i cant send you my session. The demosite does not work when pressing edit.

**Comment by HarelM** [comment]
Thanks! I'll look into it. Weird...

**Comment by HarelM** [comment]
You can have a look at the following - almost complete example (missing css)
https://stackblitz.com/edit/angular-ivy-fpge8r?file=src%2Findex.html

**Comment by DataPhaseDan** [comment]
Thanks

**Comment by HarelM** [comment]
I've fixed a few problems but for some reason the dependencies in stack blitz are at 12 while the project needs 13.
Can't find anything on it in Google though... :-/

**Comment by DataPhaseDan** [comment]
it finally works, btw on mapbox demosite is the same problem seems probably a issue with the bootstraping of the angular project on stackblitz
https://wykks.github.io/ngx-mapbox-gl/
thanks for your help.

**Comment by HarelM** [comment]
Yea, I think there's a problem with the defaults of stackblitz.
It adds angular 12 default dependencies while using 13 for the extra dependencies that are requested by the embedded page.
Also there's a breaking change in terms of how you can dynamically add components.
I'll open an issue there and direct them to the PR I created here so they can look and let me know if I should improve anything...
